name: Test

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2 
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          
      - run: |
          npm ci
          npm run lint
          npm test
         
          
      - name: Check Branch Coverage
        id: coverage
        uses: amdigital-co-uk/code-coverage-action@v1.0
        with:
          path: coverage/cobertura-coverage.xml
          branch_minimum_threshold: 0
